### ISSUE TITLE
default value of meta name robots should be index, follow

### ISSUE THREAD

**Issue by rene-dhemant** [iworks/simple-seo-improvements#2]
currently in default there is _no_ value set, causing that a meta name robots directive is _not existant_ within raw and rendered HTML. 

Only if a page or post is set to value "noindex" for example the element meta name robots gets set with that value.

The default value for all post and page types should be:

`<meta name="robots" content="index, follow" />`

and the plugin should assure, that the element is always set. 

<label-enhancement>

**Comment by iworks** [comment]
Hi @rene-dhemant 

Thank you, but according to documentation:

> The default values are index, follow and don't need to be specified.

More: https://developers.google.com/search/docs/crawling-indexing/special-tags

**Comment by rene-dhemant** [comment]
Yeah, i'm aware of the documentation and that GoogleBot treats it "default" index, follow if the meta-element robots is not set.

Do other Crawlers treat it the same way? However, it would be a small but helpful enhancement of the plugin. 

At least in my specific use case i've to swap plugins.

Thanks!
